version: '3'
services:
  nexus:
    container_name: nexus
    image: getjv/nexus3
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
volumes:
  nexus-data: 